### ISSUE TITLE
Existing databases are overridden at VM startup

### ISSUE THREAD

**Issue by cycomarcooo** [themejuice/graft#12]
This commit seems to be wrong: c55c651
Existing databases should not be overidden by /script/import-db.sh but in fact, starting from the commit mentioned above, they are. Which is very anoying, for example if the VM crashes or similar.
This script works as expected:
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/database/import-sql.sh

**Comment by ezekg** [comment]
You're right. Would you mind creating a pull request to fix that? Then I can get a new release out.
